awslabs/aws-lambda-web-adapter

.github/workflows/pipeline.yml, README.md, src/main.rs
=> add linting in GitHub actions

examples/springboot/template.yaml
Use maximum value for ProvisionedConcurrencyUtilization to scale PC faster
=> [SpringBoot Example] use customized metrics to scale Provisioned Concurrency

Cargo.lock, Cargo.toml, Dockerfile.mac, examples/expressjs-zip/hello-world/app.js, examples/expressjs/app/Dockerfile, examples/flask/app/Dockerfile, examples/nginx/app/Dockerfile, examples/php/docker/Dockerfile, examples/springboot/app/Dockerfile, src/main.rs
Solve issues: #19 #20 
upgrade to lambda_http v0.5.1
=> upgrade to lambda_http v0.5.1

.github/workflows/pipeline.yaml, README.md, examples/expressjs-zip/README.md, examples/expressjs-zip/template.yaml, template-arm64.yaml, template-x86_64.yaml
=> make layers public

.github/workflows/pipeline.yaml, Makefile
=> update pipeline to publish OCI images to ECR public repo

README.md
=> Update project name in README file

src/main.rs
Issue #39 
At cold start, Adapter will send GET request to the web app. With this change, Adapter will verify that the http response web application returns is successful (2xx). 
=> readiness check verify the http status code is successful (2xx)

src/main.rs
Close #40 
Reduce idle connection pool time on the http client talking to the web application. Express.js server has 5 seconds keep alive duration. Reqwest client has 90 seconds pool time for idle connections. This PR reduce that to 4 seconds. 
=> reduce idle connection pool time to 4 seconds

Cargo.toml, README.md, src/main.rs
Close #35 
support async init for high cold start lambda functions
=> support async init for long initialization lambda functions

Dockerfile, Dockerfile.builder, Makefile
GitHub build is failing because of not being able to download musl cross compiler. This PR fix it by use a prebuild `rust-builder` image.  
=> fix github build issue

template-arm64.yaml, template-x86_64.yaml
keep layer version permission for old layer versions. 
=> fix Adapter Layer Version Permission

template-x86_64.yaml
This keeps the number of compatible runtimes within limits.
=> remove python3.6 from compatible runtimes for x86 layer

.rustfmt.toml, Cargo.lock, Cargo.toml, Makefile, rustfmt.toml, src/lib.rs, src/main.rs
This change moves the main codebase into a library to help with reusability.
This way the adapter can be used independently of the main app.
This change also replaces the `log` crate with `tracing`, which is more widely used in the lambda echosystem.
Signed-off-by: David Calavera <david.calavera@gmail.com>
=> Extract logic into a library.

src/lib.rs
The new readiness check function error out on the first request to web server. The readiness check needs to retry the check repeatly. 
=> fix readiness check function

Cargo.lock, Cargo.toml, src/lib.rs
There are currently two blocking calls that will prevent the adapter to utilize the Tokio scheduler correctly.
This change removes those calls by using Arc and AtomicBool when necessary.
Signed-off-by: David Calavera <david.calavera@gmail.com>
=> Remove blocking calls

Cargo.lock, Cargo.toml, src/main.rs
use RUST_LOG to configure the log level and also keep the target in the debug log. 
=> configure log level with RUST_LOG environment variable

src/lib.rs, src/main.rs
Remove the dependency of lambda_http to run the adapter, so people don't have to import that crate only to call lambda_http::run.
Signed-off-by: David Calavera <david.calavera@gmail.com>
=> Hide run instruction

examples/rust-axum-zip/Cargo.lock, examples/rust-axum-zip/Cargo.toml
Update axum to 0.5.16 to address the following issue: 
axum-core has no default limit put on request bodies
=> update axum version to 0.5.16

Cargo.lock, Cargo.toml, src/lib.rs
This helps debugging when the transformation between lambda and the server doesn't work correctly.
Signed-off-by: David Calavera <david.calavera@gmail.com>
=> Add more debug information for req/res transformations

README.md, examples/flask-zip/.gitignore, examples/flask-zip/README.md, examples/flask-zip/app/Makefile, examples/flask-zip/app/app.py, examples/flask-zip/app/requirements.txt, examples/flask-zip/app/run.sh, examples/flask-zip/events/event.json, examples/flask-zip/template.yaml
=> add an example for flask in zip

Cargo.lock, Cargo.toml
upgrade to lambda_http v0.7.1 to pass correct x-ray trace id header
=> upgrade to lambda_http v0.7.1 to pass correct x-ray trace id header

README.md, src/lib.rs
Pass readiness check if the web app gives an HTTP response (any status code)
This is based on the feedback from [awslabs/aws-lambda-go-api-proxy/#143](https://github.com/awslabs/aws-lambda-go-api-proxy/issues/143)
=> relax readiness check for HTTP

Cargo.lock, Cargo.toml, src/lib.rs, tests/events.rs, tests/integ_tests.rs
**Description of changes:**
Added integration tests for the HTTP adapter using an HTTP [mock server](https://docs.rs/httpmock/latest/httpmock/). The mock server simulates the web application and it actually spins up a Hyper server locally so the tests are excercising the majority of the adapter logic, except for the part where we register as a Lambda extension (see note 2 below).
**Note**
I made a minor change to the `AdapterOptions` struct to make fields public so that we could initialize the struct from within the tests. Using environment variables for the tests wasn't an option as by default all tests run in parallel and modifying env variables in one test affects the rest of them. 
**Note 2**
I tried to simulate the Lambda Extensions API locally as well and made really good progress, …
=> Added integration tests for http adapter

.rustfmt.toml, Cargo.lock, Cargo.toml, Makefile, src/lib.rs, tests/integ_tests.rs
replace lambda-extension crate with inline extension client to reduce binary size by another 1MB. 
```
-rwxr-xr-x  1 sunhua  staff   3.7M Jan  7 13:22 target/release/lambda-adapter
```
Upgrade tokio to 1.24 for improved performance
=> rewrite extension client and upgrade tokio

.github/workflows/pipeline.yaml, template-arm64.yaml, template-x86_64.yaml, tests/e2e/fixtures/go-httpbin-zip/template.yaml, tests/e2e/fixtures/go-httpbin/app/Dockerfile
Update pipeline to pull adapter images from private ecr repo
=> Update pipeline to pull adapter images from private ecr repo during e2e test

.github/workflows/pipeline.yaml
GItHub Action actions/upload-artifact does not maintain file permission when uploading files. The workaround is to create a Tarball and upload it. 
=> Tar the build artifacts to maintain file permission

.github/workflows/pipeline.yaml
This PR adds [Foresight](https://www.runforesight.com) "workflow-kit" [action](https://github.com/runforesight/foresight-workflow-kit-action) into jobs in the `Pipeline` (`pipeline.yml`) workflow.
So Foresight will be able to collect host metrics (CPU, memory and I/O) and process traces to provide more CI pipeline insights.
=> Add Foresight workflow-kit action to collect metrics and traces

.config/nextest.toml, .github/workflows/pipeline.yaml
Switch test runner to nextest and generate junit test reports
=> Use nextest as test runner to get junit test reports

.github/workflows/pipeline.yaml
The PR adds [Foresight](https://www.runforesight.com/) "test-kit" [action](https://github.com/runforesight/foresight-test-kit-action) into jobs where tests are running in the Pipeline (pipeline.yml) workflow. The test-kit action uses the generated `junit` report to parse the tests' details. It'll work similar to workflow-kit action that's already been introduced.
I've only been able to test this with the unit tests as the e2e tests requires credentials for the environment setup. Hopefully, we won't encounter any issue regarding this.
=> Add Foresight Test Kit Action

Cargo.lock, Cargo.toml, src/lib.rs, tests/integ_tests.rs
lambda-http runtime supports `Response<hyper::Body>`. By returning app response directly, we simplified the logic in the Adapter.
=> Return app response directly to lambda-http runtime

src/lib.rs
Refactor Tower.Service call method to make easier to read
=> Refactor Tower.Service call method

Cargo.lock, Cargo.toml, README.md, src/lib.rs, tests/e2e/fixtures/go-httpbin-zip/template.yaml, tests/e2e/fixtures/go-httpbin/template.yaml, tests/e2e/main.rs, tests/integ_tests.rs
*Issue #, if available:* None
- Compress responses when the `COMPRESSION` env var is `true`, when the response is not already compressed, and when the `content-type` starts with `text/` or is one of a few known types such as `application/javascript`
- The list of mime types to compress is not configurable to align with the way CloudFront handles automatic compression if enabled - the list of mime types that should / should not be compressed is something that is largely configurable one time and does not need to be adjusted or excruciatingly specified by each consumer (like nginx requires)
- Set the `Content-Length` response header to have the correct compressed length
- Set the `Content-Encoding` response header to `gzip` if compression is performed
- This …
=> Optional gzip compression of responses

src/lib.rs, src/main.rs
This prevents issues when ca certs are not available in custom docker images.
=> Separate HTTPS and HTTP adapters

Cargo.lock, Cargo.toml, src/lib.rs, tests/integ_tests/main.rs
This PR adds support for Lambda Streaming Response. I switched the response compression to `tow_http::compression::CompressionLayer`, because it supports the streaming body.
close #203 
=> Add streaming response support

src/lib.rs
close #141 
Tighten HTTP readiness check: 
500 > status >= 100 => ready
otherwise => not ready
This will avoid issues when nginx proxing a web app and the web app is slow to start.
=> Tighten HTTP readiness check

src/lib.rs
close #155 
Add "AWS_LWA_" prefix to all environment variables to avoid conflicts with application code.We will support all the original environment variables until the project reaches v1.0.
=> Namespacing all environment variables

examples/fastapi/template.yaml
N/A
I found an oversight in the FastAPI example, which appears to be a remnant from a copied Flask example. This PR updates the description of the CloudFormation Stack in the sam template to accurately reflect the example of FastAPI implementation.
=> Fix FastAPI description in the sam template.

src/lib.rs, tests/integ_tests/main.rs
*Issue #, if available:* #245
*Description of changes:* Add `AWS_LWA_PORT` as a fallback for `readiness_check_port`.
=> Add AWS_LWA_PORT as a fallback for readiness_check_port.

src/lib.rs, tests/integ_tests/main.rs
*Issue #, if available:* #244
Made Lambda Context available to web apps in a new header (x-amzn-lambda-context).
**Note :** The implementation broke some tests because the `LambdaRequest` object used to send the request to the mock server doesn't have a lambda context, resulting in an error ("Request did not contain a lambda context") when `"let lambda_context = &event.lambda_context();"` is called. I fixed this by replacing `LambdaRequest` with `Request`, which allows adding the lambda context.
=> Pass Lambda Context to web app in a new header

README.md, src/lib.rs, tests/integ_tests/main.rs
*Issue #251*
I added an optional environment variable called AWS_LWA_READINESS_CHECK_MIN_UNHEALTHY_STATUS that will let me override the lowest status code that is considered unhealthy.  This is currently hardcoded to 500.  This PR allows me to override it.  The default remains at 500 as to not impact existing users.
=> Add option to override unhealthy status so 4xx can be unhealthy

.github/workflows/gamma.json, .github/workflows/prod.json
Deploy only the x86_64 version of the LWA layer in eu-central-2 as arm64 version is not supported yet.
=> fix: set arm64_supported to false on eu-central-2

README.md
We published LWA layers in China regions. Now we're updating the Readme with those new layers.
=> Updated Readme with new layer ARNs for China regions

.github/workflows/pipeline.yaml
=> fix: run load-china-prod-matrix2 only when release event is triggered

README.md, examples/expressjs-zip/hello-world/app.js
Update express-zip example to show Lambda Context usage
=> Update express-zip example to show Lambda Context usage

src/lib.rs, tests/integ_tests/main.rs
Currently, when a client sets their own `x-amzn-{lambda,request}-context` headers, they will be included in the request to the app server.
This request to the lambda with the adapter installed:
```
$ curl -H "x-amzn-request-context: boom" http://localhost:8000
```
Will result in this request from the adapter to the app server:
```
GET / HTTP/1.1
[...]
x-amzn-request-context: boom
x-amzn-request-context: [json context from adapter]
x-amzn-lambda-context: [json context from adapter]
[...]
```
Many implementations of web frameworks will take the *first* header when you access a header key.
For example, Starlette/FastAPI does this:
https://github.com/encode/starlette/blob/ad02ee6336faadadf97e0c79dd3a91759f1f32a7/starlette/datastructures.py#L562-L567
This patch …
=> fix: override user-set `x-amzn-{lambda,request}-context` headers

Cargo.lock, Cargo.toml, src/lib.rs, tests/e2e_tests/main.rs, tests/integ_tests/main.rs
Fix #265 
lambda-http v0.8.3 contains the fix for Content-Type processing. Upgraded to this version to fix #265. Plus refactored a few tests. 
=> Upgraded lambda-http crate to v0.8.3 to fix Content-Type processing issue

template-arm64.yaml, template-x86_64.yaml
none
add [provided.al2023](https://aws.amazon.com/blogs/compute/introducing-the-amazon-linux-2023-runtime-for-aws-lambda/) as compatible runtime for [x86_64 & arm64](https://github.com/amazonlinux/amazon-linux-2023?tab=readme-ov-file#architectures)
=> add provided.al2023 to CompatibleRuntimes

template-arm64.yaml, template-x86_64.yaml
The 'CompatibleRuntimes' property is limited to 15 values and optional. People can add this layer using the layer ARN.
=> Remove 'CompatibleRuntimes' property on the Layers

docs/development.md, src/lib.rs, src/main.rs, tests/integ_tests/main.rs
none
* set AdapterOptions with env values in Default impl
* remove borrow for consistent lets
* ~add serial_test dev-dep~
* ~run 3 tests serially to avoid mixing env vars~
=> set AdapterOptions with env values in Default impl

Dockerfile.builder
none
switch builder dockerfile to 2023 base image
=> switch builder dockerfile to 2023 base image

Makefile
fix #311 
Add correct platform parameters when building docker images.
=> Specify correct platform when building docker images

Cargo.lock, Cargo.toml, README.md, src/lib.rs, tests/e2e_tests/main.rs, tests/e2e_tests/util.rs, tests/integ_tests/main.rs
close #216 
This PR enables the adapter to pass through events from non-http triggers, such as SQS, SNS, EventBridge, and Bedrock Agents. 
Also upgrade to Hyper 1.0 and Http 1.0. 
=> Pass through events

Cargo.lock, Cargo.toml
close #317 
Update lambda-http to v0.9.2. This version fix an issue with passing through Bedrock Agent Events.
=> Update lambda-http to v0.9.2

Cargo.lock, Cargo.toml
Release the new version 0.8.1. This release contains the fix for passing through Bedrock Agent events.
=> Release v0.8.1

examples/bedrock-agent-fastapi/.gitignore, examples/bedrock-agent-fastapi/README.md, examples/bedrock-agent-fastapi/app/Dockerfile, examples/bedrock-agent-fastapi/app/main.py, examples/bedrock-agent-fastapi/app/middleware.py, examples/bedrock-agent-fastapi/app/requirements.txt, examples/bedrock-agent-fastapi/events/s3_bucket_count.json, examples/bedrock-agent-fastapi/events/s3_object.json, examples/bedrock-agent-fastapi/events/s3_object_count.json, examples/bedrock-agent-fastapi/template.yaml
#317
Add Bedrock Agent example
=> Add Bedrock Agent example

examples/gin-zip/app/Makefile, examples/gin-zip/template.yaml
Use the build-in go1.x build method supported by SAM CLI to replace the custom Makefile.
=> Update BuildMethod in gin-zip example

Cargo.lock, Cargo.toml, src/lib.rs
lambda-http 0.9.3 contains support for UTF-8 header values (https://github.com/awslabs/aws-lambda-rust-runtime/pull/800)
=> Support UTF-8 String in HTTP Header Values

examples/fastapi-response-streaming/app/main.py
Rewrite the LLM call with Claude3, and updated the response streaming parse logic as Claude3 from Bedrock response format has changed.
=> refactor: refactor the FastAPI response streaming with Claude3

examples/bedrock-agent-fastapi-zip/README.md, examples/bedrock-agent-fastapi-zip/template.yaml, examples/bedrock-agent-fastapi/README.md, examples/bedrock-agent-fastapi/template.yaml
CloudFormation is now supported deploying Agents for Amazon Bedrock.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Bedrock.html
So, I updated deploy process about sample bedrock-agent-fastapi-zip and bedrock-agent-fastapi.
=> Update deploy process Bedrock Agent (zip and container) using CloudFormation

src/lib.rs
This change removes "transfer-encoding" http header from web app response. This resolves an issue that `sam local start-api` fails to handle the chunked response from SpringBoot. 
=> Remove "transfer-encoding" header from responses

examples/bedrock-agent-fastapi-zip/app/run.sh, examples/fastapi-response-streaming-zip/app/run.sh, examples/fastapi-zip/app/run.sh, examples/flask-zip/app/run.sh
*Issue #, if available:* #453
*Description of changes:* Update the Fast API run script examples
After the change, the search path has been verified to be `['', '/var/task', '/var/runtime', '/var/lang/lib/python38.zip', '/var/lang/lib/python3.8', '/var/lang/lib/python3.8/lib-dynload', '/var/lang/lib/python3.8/site-packages']`, where `/var/runtime` is the value of `$LAMBDA_RUNTIME_DIR` and the code could work even user didn't bundle boto3 in the zip archive.
=> [#453] Update the Fast API run script examples to include LAMBDA_RUNTIME_DIR in search path.

README.md, src/lib.rs, tests/integ_tests/main.rs
#477 
Added `AWS_LWA_AUTHORIZATION_SOURCE` option to rename a specifed header name to `Authorization`. Details are in the linked issue.
=> add authorization_source feature

src/lib.rs
https://github.com/awslabs/aws-lambda-web-adapter/issues/477
missed https://github.com/awslabs/aws-lambda-web-adapter/pull/478 code review
warn when:
1. `AWS_LWA_AUTHORIZATION_SOURCE=auth-token`
2. `.with_header("other-token", "Bearer token")`
=> warn when configured header not found

.github/workflows/pipeline.yaml
=> Fix beta stack e2e tests

docs/design.md, docs/development.md
- Changing docs where it mentioned "Lambda Adapter" instead of the official name now "Lambda Web Adapter".
- Fixing a couple of minor grammatical errors. 
=> docs: Add Web to tool name in docs

README.md, src/lib.rs
AWS_LAMBDA_RUNTIME_API and use a proxy
=> feat: add AWS_LWA_PROXY_LAMBDA_RUNTIME_API to overwrite

tests/e2e_tests/fixtures/go-httpbin-zip/template.yaml
Update HttpBingFunction runtime to provided.al2023. This fixes the faling e2e tests in the pipeline. 
=> Update HttpBingFunction runtime

.github/workflows/pipeline.yaml
Replace the all [`actions/checkout@v3`](https://github.com/actions/checkout/releases/tag/v3.6.0) with [`actions/checkout@v4`](https://github.com/actions/checkout/releases/tag/v4.2.2)
=> chore: update `actions/checkout` GitHub Actions

README.md
*Issue #, if available:* N/A
A previous PR https://github.com/awslabs/aws-lambda-web-adapter/pull/602 added Datadog examples. The current PR adds links to the examples in README.
=> Add links to Datadog examples in README
