awslabs/aws-lambda-web-adapter

README.md, examples/flask/.gitignore, examples/flask/README.md, examples/flask/app/Dockerfile, examples/flask/app/app.py, examples/flask/app/requirements.txt, examples/flask/events/event.json, examples/flask/template.yaml, examples/nginx/README.md, examples/nginx/app/Dockerfile, examples/nginx/template.yaml, examples/springboot/README.md, examples/springboot/template.yaml
=> add Flask example and update README files for other examples

Cargo.lock, Cargo.toml, README.md, examples/nginx/app/config/nginx.conf, src/main.rs
support 'content-encoding' in http response
=> add support for HTTP compression

Cargo.lock, Cargo.toml, examples/expressjs-zip/hello-world/app.js, examples/expressjs/app/Dockerfile, examples/flask/app/Dockerfile, examples/nginx/app/Dockerfile, examples/php/docker/Dockerfile, examples/springboot/app/Dockerfile
#20 
remove stage from URL send to app server 
Custom User-Agent as aws-lambda-adapter/CARGO-PACKAGE-VERSION
Strip the binary to reduce size
Update examples
=> remove stage from URL send to app server + custom User-Agent

Cargo.lock, Cargo.toml, Dockerfile, README.md, examples/springboot/README.md, examples/springboot/template.yaml, src/main.rs
#10 
Support to remove base path from http request path, by configuring environment variable `REMOVE_BASE_PATH`.
=> support to remove base path from http request path 

Makefile, README.md, examples/expressjs-zip/adapter/bootstrap, examples/expressjs-zip/hello-world/run.sh, examples/expressjs-zip/template.yaml, layer/bootstrap
=> update expressjs-zip example using the new adapter layer

Dockerfile
That way we can get usage metrics for both projects.
Signed-off-by: David Calavera <dcalaver@amazon.com>
=> Preserve aws-lambda-rust in the user-agent

.rustfmt.toml, src/main.rs
#38 
readness_check_port defaults to port
=> readness_check_port defaults to port

Cargo.toml
Close #42 
upgrade to Rust 2021 edition
=> upgrade to Rust 2021 edition

examples/expressjs-zip/template.yaml, examples/expressjs/app/Dockerfile, examples/flask/app/Dockerfile, examples/nginx/app/Dockerfile, examples/php/docker/Dockerfile, examples/springboot-zip/template.yaml, examples/springboot/app/Dockerfile
Update examples to version 0.3.3
=> Update examples to version 0.3.3

Dockerfile, Dockerfile.builder, Makefile
=> Fix build command

Cargo.lock, Cargo.toml, src/main.rs
=> add metadata for crates.io

README.md
PHP is spelled all caps, minor fix :)
=> Fix casing in README

Cargo.lock, Cargo.toml
=> release v0.4.0

README.md, examples/expressjs-zip/template.yaml, examples/expressjs/app/Dockerfile, examples/flask/app/Dockerfile, examples/nextjs-zip/template.yaml, examples/nextjs/app/Dockerfile, examples/nginx/app/Dockerfile, examples/php/docker/Dockerfile, examples/rust-axum-zip/template.yaml, examples/springboot-zip/template.yaml, examples/springboot/app/Dockerfile
update README and examples to v0.4.0
=> update README and examples to v0.4.0

src/lib.rs, src/main.rs
change register_default_extension() as a method on Adapter
=> change register_default_extension() as a method on Adapter

README.md, src/lib.rs
add option READINESS_CHECK_PROTOCOL to support "tcp" readiness check
Resolve #82 
=> Add tcp  readiness check

Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> Release v0.4.1

README.md
=> update README for v0.4.1

Cargo.lock, Cargo.toml, src/lib.rs
Make the response future to be Send.
Signed-off-by: David Calavera <dcalaver@amazon.com>
=> Upgrade to lambda_http 0.7

Cargo.lock, Cargo.toml, README.md, examples/expressjs-zip/README.md, examples/expressjs-zip/template.yaml, examples/expressjs/README.md, examples/expressjs/app/Dockerfile, examples/fastapi-zip/README.md, examples/fastapi-zip/template.yaml, examples/fastapi/README.md, examples/fastapi/app/Dockerfile, examples/flask-zip/README.md, examples/flask-zip/template.yaml, examples/flask/README.md, examples/flask/app/Dockerfile, examples/gin-zip/template.yaml, examples/gin/app/Dockerfile, examples/nextjs-zip/template.yaml, examples/nextjs/app/Dockerfile, examples/nginx/README.md, examples/nginx/app/Dockerfile, examples/php/docker/Dockerfile, examples/rust-axum-zip/template.yaml, examples/springboot-zip/README.md, examples/springboot-zip/template.yaml, examples/springboot/README.md, examples/springboot/app/Dockerfile
=> Release 0.5.0

Cargo.toml
Bump adapter version to v0.5.1.
=> release v0.5.1

Cargo.lock, Cargo.toml, src/lib.rs
close #107 
This PR forwards RequestContext to web app in http header "x-amzn-request-context"
=> forward RequestContext in a http header

README.md, examples/expressjs-zip/README.md, examples/expressjs-zip/hello-world/app.js, examples/expressjs-zip/template.yaml, examples/expressjs/README.md, examples/expressjs/app/Dockerfile, examples/fastapi-zip/README.md, examples/fastapi-zip/template.yaml, examples/fastapi/README.md, examples/fastapi/app/Dockerfile, examples/flask-zip/README.md, examples/flask-zip/template.yaml, examples/flask/README.md, examples/flask/app/Dockerfile, examples/gin-zip/template.yaml, examples/gin/app/Dockerfile, examples/nextjs-zip/template.yaml, examples/nextjs/app/Dockerfile, examples/nginx/README.md, examples/nginx/app/Dockerfile, examples/php/docker/Dockerfile, examples/rust-axum-zip/template.yaml, examples/springboot-zip/README.md, examples/springboot-zip/app/src/main/resources/run.sh, examples/springboot-zip/template.yaml, examples/springboot/README.md, examples/springboot/app/Dockerfile
Added a section about Request Context in README.md. Updated all examples to use v0.6.0 release.
=> update README and examples for v0.6.0

Cargo.lock, Cargo.toml
=> bump release version to 0.6.0

examples/php/app/html/index.php
*Description of changes:* 
- Removed redundant closing tag. According to the PSR, closing tag are not normally used.
- Format code by PSR.
=> Removed redundant closing tag & Format code by PSR

README.md, examples/expressjs-zip/README.md, examples/expressjs-zip/template.yaml, examples/expressjs/README.md, examples/expressjs/app/Dockerfile, examples/expressjs/app/src/package-lock.json, examples/fastapi-zip/README.md, examples/fastapi-zip/template.yaml, examples/fastapi/README.md, examples/fastapi/app/Dockerfile, examples/flask-zip/README.md, examples/flask-zip/template.yaml, examples/flask/README.md, examples/flask/app/Dockerfile, examples/gin-zip/template.yaml, examples/gin/app/Dockerfile, examples/nextjs-zip/template.yaml, examples/nextjs/app/Dockerfile, examples/nginx/README.md, examples/nginx/app/Dockerfile, examples/php/docker/Dockerfile, examples/rust-axum-zip/template.yaml, examples/springboot-zip/README.md, examples/springboot-zip/template.yaml, examples/springboot/README.md, examples/springboot/app/Dockerfile
Update README and examples to v0.6.1
=> Update README and examples to v0.6.1

.github/workflows/pipeline.yaml
Update pipeline to fix matrix variables
=> Update pipeline to fix matrix variables

.github/workflows/pipeline.yaml, template-arm64.yaml, template-x86_64.yaml, tests/e2e/fixtures/go-httpbin-zip/template.yaml, tests/e2e/fixtures/go-httpbin/app/Dockerfile
Update pipeline to actually test the latest layers and images in beta enironment. 
=> Update pipeline to test the latest layers and images

README.md, examples/deno-zip/README.md, examples/deno-zip/src/Makefile, examples/deno-zip/src/main.ts, examples/deno-zip/template.yaml
Add a new example: Deno Oak in Zip with SnapStart
=> Add Deno Oak in Zip example

examples/fastapi-zip/app/Makefile, examples/fastapi-zip/app/run.sh, examples/fastapi-zip/template.yaml, examples/flask-zip/app/Makefile, examples/flask-zip/app/requirements.txt, examples/flask-zip/app/run.sh, examples/flask-zip/template.yaml, examples/flask/app/requirements.txt
Upgrade Flask to resolve security warnings. 
=> Upgrade Flask

Cargo.lock, Cargo.toml
=> release v0.6.2

README.md, examples/deno-zip/README.md, examples/deno-zip/template.yaml, examples/expressjs-zip/README.md, examples/expressjs-zip/template.yaml, examples/expressjs/README.md, examples/expressjs/app/Dockerfile, examples/fastapi-zip/README.md, examples/fastapi-zip/template.yaml, examples/fastapi/README.md, examples/fastapi/app/Dockerfile, examples/flask-zip/README.md, examples/flask-zip/template.yaml, examples/flask/README.md, examples/flask/app/Dockerfile, examples/gin-zip/template.yaml, examples/gin/app/Dockerfile, examples/nginx/README.md, examples/nginx/app/Dockerfile, examples/php/docker/Dockerfile, examples/rust-axum-zip/template.yaml, examples/springboot-zip/README.md, examples/springboot-zip/template.yaml, examples/springboot/README.md, examples/springboot/app/Dockerfile
Update README and examples for v0.6.2
=> Update README and examples for v0.6.2

Cargo.lock, Cargo.toml, src/lib.rs, tests/integ_tests.rs
close #173 
Use url crate to handle app url encoding
=> Use url crate to handle app url encoding

Cargo.lock, README.md
close #179 
Document ports should be avoided
=> Document ports should be avoided

README.md
close #125 
Add a short notes about local debugging with sam local
=> Document local debugging with aws sam local

Cargo.lock, Cargo.toml
=> Release v0.6.3

README.md, examples/deno-zip/README.md, examples/deno-zip/template.yaml, examples/expressjs-zip/README.md, examples/expressjs-zip/template.yaml, examples/expressjs/README.md, examples/expressjs/app/Dockerfile, examples/fastapi-zip/README.md, examples/fastapi-zip/template.yaml, examples/fastapi/README.md, examples/fastapi/app/Dockerfile, examples/flask-zip/README.md, examples/flask-zip/template.yaml, examples/flask/README.md, examples/flask/app/Dockerfile, examples/gin-zip/template.yaml, examples/gin/app/Dockerfile, examples/nextjs-zip/template.yaml, examples/nextjs/app/Dockerfile, examples/nginx/README.md, examples/nginx/app/Dockerfile, examples/php/docker/Dockerfile, examples/rust-actix-web-zip/template.yaml, examples/rust-axum-zip/template.yaml, examples/springboot-zip/README.md, examples/springboot-zip/template.yaml, examples/springboot/README.md, examples/springboot/app/Dockerfile
=> Update examples to v0.6.3

Cargo.lock, Cargo.toml
=> Prepare to release v0.6.4

.github/workflows/pipeline.yaml
Use Ubuntu 20.04 for builds in GitHub Actions
=> Use Ubuntu 20.04 for builds

.github/workflows/pipeline.yaml
Update pipeline to remove foresight integration
=> Update pipeline to remove foresight integration

examples/fastapi-response-streaming/.gitignore, examples/fastapi-response-streaming/README.md, examples/fastapi-response-streaming/app/main.py, examples/fastapi-response-streaming/app/requirements.txt, examples/fastapi-response-streaming/app/run.sh, examples/fastapi-response-streaming/template.yaml
Add FastAPI response streaming example
=> Add FastAPI response streaming example

Cargo.lock, Cargo.toml
=> Bump version to v0.7.0

examples/expressjs-zip/hello-world/app.js
=> Handle readiness check

examples/flask-zip/app/requirements.txt, examples/flask-zip/template.yaml, examples/flask/app/requirements.txt, examples/flask/template.yaml
=> Upgrade Flask to 2.3.2

examples/fastapi-https/app/requirements.txt, examples/fastapi-response-streaming/app/requirements.txt, examples/fastapi-zip/app/requirements.txt, examples/fastapi/app/requirements.txt
upgrade FastAPI in examples to resolve security issues
=> Upgrade FastAPI in examples

.github/workflows/gamma.json, .github/workflows/prod.json
- Updated Github actions to publish LWA in all new regions, except china regions (coming next)
- Updated Github actions to publish LWA arm64 version in all supported regions.
=> Update github actions to publish lambda web adapter in all new regions

.github/workflows/pipeline.yaml
=> fix: update pipeline file to run package-china-gamma before load-china-gamma-matrix2

.github/workflows/pipeline.yaml
=> fix: deploy to china gamma accounts when PR is merged to main branch

Cargo.toml
=> Bump crate version to 0.7.1

Cargo.toml
=> bump version to v0.7.2

.github/workflows/pipeline.yaml, Makefile, template-arm64.yaml, template-x86_64.yaml
- Use cargo lambda for building
- add sccache for caching
- Do not trigger this pipeline for changes in 'doc' and 'examples' directories.
=> Optimize GitHub Actions workflow

README.md, examples/sqs-expressjs/.gitignore, examples/sqs-expressjs/README.md, examples/sqs-expressjs/app/Dockerfile, examples/sqs-expressjs/app/src/index.js, examples/sqs-expressjs/app/src/package-lock.json, examples/sqs-expressjs/app/src/package.json, examples/sqs-expressjs/events/sqs.json, examples/sqs-expressjs/template.yaml
=> Add SQS-Expressjs example

Cargo.lock, Cargo.toml
=> Bump version to 0.8.0

README.md
close #247 
Add information about how to subscribe for new layer notifications
=> Add info about new layer notifications

.github/workflows/pipeline.yaml, Makefile
Update pipeline to fix the last job
=> Update GitHub Actions Pipeline

README.md, examples/bedrock-agent-fastapi/README.md
Update README to mention Bedrock Agent FastAPI
=> Update README to mention Bedrock Agent FastAPI Example

examples/sinatra/.gitignore, examples/sinatra/README.md, examples/sinatra/app/Dockerfile, examples/sinatra/app/src/Gemfile, examples/sinatra/app/src/Gemfile.lock, examples/sinatra/app/src/app.rb, examples/sinatra/template.yml
Add examples for Sinatra (web application framework in Ruby) applications using the Lambda Web Adapter
=> Add Sinatra examples

examples/go-http-zip/README.md, examples/go-http-zip/cmd/website/main.go, examples/go-http-zip/go.mod, examples/go-http-zip/template.yml
I added a simple Golang example using the `net/http` core package and zip method.
=> added go-http example

examples/go-http-zip/template.yml
Add GoWebsiteAPI URL output in the SAM template
=> Add output to template.yml

.github/workflows/security_audit.yaml, Cargo.lock
=> Add daily security audit

.github/workflows/security_audit.yaml
=> Upgrade audit-check action

examples/fastapi-background-tasks/app/main.py
Returen 201 status code correctly
=> Returen 201 status code correctly

README.md
document support for non aws base images
=> doc base image build option

Cargo.lock, Cargo.toml
=> bump version to 0.8.2

README.md
=> Update README for 0.8.2

examples/javalin-zip/README.md, examples/javalin-zip/app/.gitignore, examples/javalin-zip/app/pom.xml, examples/javalin-zip/app/src/main/java/com/amazonaws/demo/petstore/Application.java, examples/javalin-zip/app/src/main/java/com/amazonaws/demo/petstore/controller/PetsController.java, examples/javalin-zip/app/src/main/java/com/amazonaws/demo/petstore/model/Error.java, examples/javalin-zip/app/src/main/java/com/amazonaws/demo/petstore/model/Pet.java, examples/javalin-zip/app/src/main/java/com/amazonaws/demo/petstore/model/PetData.java, examples/javalin-zip/app/src/main/resources/run.sh, examples/javalin-zip/template.yaml
*Issue #:* Not available
*Description of changes:* Added an example on using Javalin version 6 with the aws-lambda-web-adapter project
=> Javalin 6 example using Arm64 image

examples/fastapi-response-streaming-zip/app/run.sh, examples/fastapi-zip/app/run.sh, examples/flask-zip/app/run.sh
*Issue* #441
Update init script to make dependencies from `/opt/python` discoverable.
=> Example Fix: python dependencies from layers

Cargo.lock, Cargo.toml
=> Bump version to 0.8.3

Cargo.lock, Cargo.toml
=> Bump the version to v0.8.4

.github/CODEOWNERS, .github/workflows/pipeline.yaml
Fix workflow error and replace several GitHub Actions
=> Update GitHub Actions

examples/fasthtml-response-streaming/app/main.py
Read aws region from env var AWS_REGION instead of hard code the region to "us-east-1"
=> Read aws region from env var

Cargo.lock, Cargo.toml, README.md
=> Bump version to v0.9.0

.github/workflows/pipeline.yaml, Cargo.lock, Cargo.toml
=> bump version to 0.9.1
